######################################################################
##
## Filename: siggen_tb.udo
## Created on: Wed Apr 13 05:19:54 PM CST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
