######################################################################
##
## Filename: vec_generator_tb.udo
## Created on: Mon Apr 18 03:55:19 PM CST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
