######################################################################
##
## Filename: vec_generator.udo
## Created on: Mon Apr 18 04:31:05 PM CST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
