# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/mul_13bits/mul_13bits.xci
# IP: The module: 'mul_13bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/mul_13bits/mul_13bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_13bits'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/mul_13bits/mul_13bits.xci
# IP: The module: 'mul_13bits' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/mul_13bits/mul_13bits_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mul_13bits'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
