######################################################################
##
## Filename: siggen_tb.udo
## Created on: Tue Mar 29 10:24:18 AM CST 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
