# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7vx485tffg1157-1
set_property target_language Verilog [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files /home/david/Desktop/siggen-v2-vivado/ipcore_dir/bram_B/B/B.coe
add_files /home/david/Desktop/siggen-v2-vivado/ipcore_dir/bram_B/B_aux/B_aux.coe
add_files /home/david/Desktop/siggen-v2-vivado/ipcore_dir/bram_A/A/A.coe
add_files /home/david/Desktop/siggen-v2-vivado/ipcore_dir/bram_2bits/b.coe
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/B_synth_1/B.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/B_synth_1/B.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/B_aux_synth_1/B_aux.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/B_aux_synth_1/B_aux.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/A_synth_1/A.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/A_synth_1/A.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/A_aux_synth_1/A_aux.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/A_aux_synth_1/A_aux.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/fifo_8_to_1_synth_1/fifo_8_to_1.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/fifo_8_to_1_synth_1/fifo_8_to_1.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/mul_13bits_synth_1/mul_13bits.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/mul_13bits_synth_1/mul_13bits.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/mul_32bit_synth_1/mul_32bit.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/mul_32bit_synth_1/mul_32bit.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/fifo_13_to_13_synth_1/fifo_13_to_13.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/fifo_13_to_13_synth_1/fifo_13_to_13.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/div_synth_1/div.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/div_synth_1/div.dcp]
add_files -quiet /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/b_2bit_synth_1/b_2bit.dcp
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.runs/b_2bit_synth_1/b_2bit.dcp]
read_verilog -library xil_defaultlib {
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/best_d.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/encoder_main.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/CWEncode.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/vec_generator.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/syngen.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/qc_shifter.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/prng_lcg.v
  /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/imports/src/siggen.v
}
read_xdc /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/constrs_1/new/siggen.xdc
set_property used_in_implementation false [get_files /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/constrs_1/new/siggen.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.cache/wt [current_project]
set_property parent.project_dir /home/david/Desktop/siggen-v2-vivado [current_project]
catch { write_hwdef -file siggen.hwdef }
synth_design -top siggen -part xc7vx485tffg1157-1
write_checkpoint siggen.dcp
report_utilization -file siggen_utilization_synth.rpt -pb siggen_utilization_synth.pb
