# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13.xci
# IP: The module: 'fifo_13_to_13' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13/fifo_13_to_13.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_13_to_13'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_13_to_13'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13.xci
# IP: The module: 'fifo_13_to_13' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13/fifo_13_to_13.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_13_to_13'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/david/Desktop/siggen-v2-vivado/siggen-v2-vivado.srcs/sources_1/ip/fifo_13_to_13/fifo_13_to_13_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_13_to_13'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
